-- FINAL DIRECT SQL IMPORT
-- Run this in the Supabase SQL Editor to fill the league instantly.

INSERT INTO public.users_profiles (id, display_name, fargo_rating, spot_rank) VALUES
(uuid_generate_v4(), 'Dan Hamper', 637, 1),
(uuid_generate_v4(), 'Frank Kincl', 626, 2),
(uuid_generate_v4(), 'David Smith', 616, 3),
(uuid_generate_v4(), 'Mike Paliga', 586, 4),
(uuid_generate_v4(), 'Dave Alderman', 580, 5),
(uuid_generate_v4(), 'Josh Fava', 572, 6),
(uuid_generate_v4(), 'Timmy Squires', 558, 7),
(uuid_generate_v4(), 'Chase Dalin', 540, 8),
(uuid_generate_v4(), 'Randy Hoag', 512, 9),
(uuid_generate_v4(), 'Jerry Sabol', 502, 10),
(uuid_generate_v4(), 'Kurt Kubicka', 492, 11),
(uuid_generate_v4(), 'Zach Ledesma', 492, 12),
(uuid_generate_v4(), 'Steve Adsem', 487, 13),
(uuid_generate_v4(), 'Walter Ryan Isenhour', 478, 14),
(uuid_generate_v4(), 'Nate Welch', 476, 15),
(uuid_generate_v4(), 'Thomas E. Kingston', 475, 16),
(uuid_generate_v4(), 'Mike Zahn', 473, 17),
(uuid_generate_v4(), 'Christina Talbot', 469, 18),
(uuid_generate_v4(), 'Josh Hill', 455, 19),
(uuid_generate_v4(), 'Matt Gilbert', 450, 20),
(uuid_generate_v4(), 'Sarah Urbaniak VanCleave', 447, 21),
(uuid_generate_v4(), 'Jesse Chandler', 444, 22),
(uuid_generate_v4(), 'Anthony Jacobs', 440, 23),
(uuid_generate_v4(), 'Joel Selzer', 429, 24),
(uuid_generate_v4(), 'Jon Nash', 418, 25),
(uuid_generate_v4(), 'Joe Mackay', 417, 26),
(uuid_generate_v4(), 'Marc Sanche', 413, 27),
(uuid_generate_v4(), 'James Ellington', 408, 28),
(uuid_generate_v4(), 'Walker Hopkins', 407, 29),
(uuid_generate_v4(), 'Troy Jacobs', 403, 30),
(uuid_generate_v4(), 'Tizer Rushford', 401, 31),
(uuid_generate_v4(), 'George Cotton', 399, 32),
(uuid_generate_v4(), 'Keenen Blackbird', 388, 33),
(uuid_generate_v4(), 'Janice Osborne', 378, 34),
(uuid_generate_v4(), 'Chris Gomez', 372, 35),
(uuid_generate_v4(), 'Josh Waples', 369, 36),
(uuid_generate_v4(), 'Sady Garrison', 329, 37),
(uuid_generate_v4(), 'Kelly Smail', 303, 38),
(uuid_generate_v4(), 'Makayla Ledford', 294, 39),
(uuid_generate_v4(), 'Heather Jarvis', 293, 40),
(uuid_generate_v4(), 'Samantha Chase', 241, 41),
(uuid_generate_v4(), 'Courtney Norman', 230, 42),
(uuid_generate_v4(), 'Steven Ross Brandenburg', -90, 43),
(uuid_generate_v4(), 'Tim Webster', 0, 44),
(uuid_generate_v4(), 'Eric Croft', 0, 45),
(uuid_generate_v4(), 'Louise Broksle', 0, 46),
(uuid_generate_v4(), 'Vern Carpenter', 0, 47),
(uuid_generate_v4(), 'Mike Churchill', 0, 48),
(uuid_generate_v4(), 'Gurn Blanston', 0, 49),
(uuid_generate_v4(), 'Rob Millions', 0, 50),
(uuid_generate_v4(), 'Patrick Donald', 0, 51),
(uuid_generate_v4(), 'Tim Gregor', 0, 52),
(uuid_generate_v4(), 'James McMasters', 0, 53),
(uuid_generate_v4(), 'James Smith', 0, 54),
(uuid_generate_v4(), 'Lea Hightshoe', 0, 55),
(uuid_generate_v4(), 'Kenny Thurman', 0, 56),
(uuid_generate_v4(), 'Roger Simmons', 0, 57),
(uuid_generate_v4(), 'Justin Cavazos', 0, 58),
(uuid_generate_v4(), 'Sean Royston', 0, 59),
(uuid_generate_v4(), 'Clayton Carter', 0, 60),
(uuid_generate_v4(), 'Ryan Fields', 0, 61),
(uuid_generate_v4(), 'Kris Vladic', 0, 62),
(uuid_generate_v4(), 'Jennifer Lynn', 0, 63),
(uuid_generate_v4(), 'Justin Whittenberg', 0, 64),
(uuid_generate_v4(), 'Kenrick Leistiko', 0, 65),
(uuid_generate_v4(), 'Richard Frankforter', 0, 66),
(uuid_generate_v4(), 'Brandon Lucas Parker', 0, 67),
(uuid_generate_v4(), 'Anita Scharf', 0, 68),
(uuid_generate_v4(), 'Ileana Hernandez', 0, 69)
ON CONFLICT (spot_rank) DO UPDATE SET 
    display_name = EXCLUDED.display_name,
    fargo_rating = EXCLUDED.fargo_rating;
